name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  display-python-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Display Python version
      run: python --version

  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pylint
      run: pylint app.py

    - name: Test Flask application
      run: |
        python app.py &
        sleep 5
        curl http://localhost:5000
        pkill -f "python app.py"
