name: Python and Pylint Workflow

on:
  push:
    branches: [ main ]

jobs:
  display_python_version:
    runs-on: ubuntu-latest
    steps:
    - name: Display Python version
      run: python --version
  pylint_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Pyplint
      run: pylint app.py
